language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
      - php: hhvm
env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit --coverage-text
