language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  include:
    - php: 5.3
      env: SYMFONY_VERSION=2.1.*
    - php: 5.3
      env: SYMFONY_VERSION=2.2.*
    - php: 5.3
      env: SYMFONY_VERSION=2.3.*
    - php: 5.3
      env: SYMFONY_VERSION=2.4.*
  allow_failures:
      - php: hhvm
env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit --coverage-text
